"""update ai_insights columns

Revision ID: 1630bf91a05b
Revises: 52b6b3d088c7
Create Date: 2026-05-16 07:06:12.621803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1630bf91a05b'
down_revision: Union[str, Sequence[str], None] = '52b6b3d088c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_insights', sa.Column('insights', sa.JSON(), nullable=False))
    op.add_column('ai_insights', sa.Column('generated_at', sa.DateTime(), nullable=False))
    op.add_column('ai_insights', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'ai_insights', ['strava_id'])
    op.drop_constraint('ai_insights_activity_id_fkey', 'ai_insights', type_='foreignkey')
    op.drop_column('ai_insights', 'insight')
    op.drop_column('ai_insights', 'activity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_insights', sa.Column('activity_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ai_insights', sa.Column('insight', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('ai_insights_activity_id_fkey', 'ai_insights', 'activities', ['activity_id'], ['strava_activity_id'])
    op.drop_constraint(None, 'ai_insights', type_='unique')
    op.drop_column('ai_insights', 'is_valid')
    op.drop_column('ai_insights', 'generated_at')
    op.drop_column('ai_insights', 'insights')
    # ### end Alembic commands ###
