"""Initial migration

Revision ID: 444de1d88458
Revises: 
Create Date: 2026-05-13 13:27:56.881346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444de1d88458'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('strava_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('strava_id'),
    sa.UniqueConstraint('strava_id')
    )
    op.create_table('activities',
    sa.Column('strava_activity_id', sa.String(), nullable=False),
    sa.Column('strava_id', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['strava_id'], ['users.strava_id'], ),
    sa.PrimaryKeyConstraint('strava_activity_id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strava_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('insight', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.strava_activity_id'], ),
    sa.ForeignKeyConstraint(['strava_id'], ['users.strava_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_insights')
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###
