"""add daily_quote_cache table

Revision ID: 52b6b3d088c7
Revises: 444de1d88458
Create Date: 2026-05-14 07:58:15.791687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b6b3d088c7'
down_revision: Union[str, Sequence[str], None] = '444de1d88458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quote_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('cached_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['strava_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('daily_quote_cache')
    # ### end Alembic commands ###
